# Dedicated image for histocell.alumine.com.br
# Serves histocell/index.html as the site root (index).
FROM nginx:alpine
COPY . /usr/share/nginx/html
COPY nginx-histocell.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
